"""core and time-series schema

Revision ID: 3d8f77f3cd0f
Revises: 
Create Date: 2026-09-07 18:22:59.338208

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3d8f77f3cd0f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stowage_factor_m3_per_t', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo_type')),
    sa.UniqueConstraint('code', name=op.f('uq_cargo_type_code'))
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source')),
    sa.UniqueConstraint('code', name=op.f('uq_data_source_code'))
    )
    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unlocode', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('max_loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cargo_handling_rate_tph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_east_coast_india', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port')),
    sa.UniqueConstraint('unlocode', name=op.f('uq_port_unlocode'))
    )
    op.create_table('vessel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dwt_min_t', sa.Integer(), nullable=True),
    sa.Column('dwt_max_t', sa.Integer(), nullable=True),
    sa.Column('typical_loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('typical_beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('typical_draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vessel_type')),
    sa.UniqueConstraint('code', name=op.f('uq_vessel_type_code'))
    )
    op.create_table('ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='run_status'), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=True),
    sa.Column('raw_object_uri', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_ingestion_run_data_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run'))
    )
    op.create_index('ix_ingestion_run_data_source_id_started_at', 'ingestion_run', ['data_source_id', 'started_at'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=False),
    sa.Column('distance_nm', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_port_id'], ['port.id'], name=op.f('fk_route_destination_port_id_port')),
    sa.ForeignKeyConstraint(['origin_port_id'], ['port.id'], name=op.f('fk_route_origin_port_id_port')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route')),
    sa.UniqueConstraint('origin_port_id', 'destination_port_id', name=op.f('uq_route_origin_port_id_destination_port_id'))
    )
    op.create_index(op.f('ix_route_destination_port_id'), 'route', ['destination_port_id'], unique=False)
    op.create_index(op.f('ix_route_origin_port_id'), 'route', ['origin_port_id'], unique=False)
    op.create_table('vessel',
    sa.Column('imo', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('vessel_type_id', sa.Integer(), nullable=True),
    sa.Column('dwt_t', sa.Integer(), nullable=True),
    sa.Column('loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_type_id'], ['vessel_type.id'], name=op.f('fk_vessel_vessel_type_id_vessel_type')),
    sa.PrimaryKeyConstraint('imo', name=op.f('pk_vessel'))
    )
    op.create_table('baltic_index_value',
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_baltic_index_value_ingestion_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('index_code', 'ts', name=op.f('pk_baltic_index_value'))
    )
    op.create_index('ix_baltic_index_value_index_code_ts', 'baltic_index_value', ['index_code', 'ts'], unique=False)
    op.create_table('bunker_price',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('fuel_grade', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_usd_per_t', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_bunker_price_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], name=op.f('fk_bunker_price_port_id_port')),
    sa.PrimaryKeyConstraint('port_id', 'fuel_grade', 'ts', name=op.f('pk_bunker_price'))
    )
    op.create_index('ix_bunker_price_port_id_fuel_grade_ts', 'bunker_price', ['port_id', 'fuel_grade', 'ts'], unique=False)
    op.create_table('charter_enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('cargo_type_id', sa.Integer(), nullable=False),
    sa.Column('cargo_quantity_t', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('laycan_start', sa.Date(), nullable=False),
    sa.Column('laycan_end', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.Enum('SPOT', 'PERIOD', name='contract_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['cargo_type.id'], name=op.f('fk_charter_enquiry_cargo_type_id_cargo_type')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_charter_enquiry_route_id_route')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charter_enquiry'))
    )
    op.create_index(op.f('ix_charter_enquiry_route_id'), 'charter_enquiry', ['route_id'], unique=False)
    op.create_table('port_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_imo', sa.String(length=7), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('berthed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turnaround_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('laytime_allowed_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('laytime_used_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('demurrage_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_port_call_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], name=op.f('fk_port_call_port_id_port')),
    sa.ForeignKeyConstraint(['vessel_imo'], ['vessel.imo'], name=op.f('fk_port_call_vessel_imo_vessel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_call')),
    sa.UniqueConstraint('vessel_imo', 'port_id', 'arrival_at', name=op.f('uq_port_call_vessel_imo_port_id_arrival_at'))
    )
    op.create_index('ix_port_call_port_id_arrival_at', 'port_call', ['port_id', 'arrival_at'], unique=False)
    op.create_table('port_congestion_metric',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vessels_waiting', sa.Integer(), nullable=False),
    sa.Column('avg_waiting_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_port_congestion_metric_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], name=op.f('fk_port_congestion_metric_port_id_port')),
    sa.PrimaryKeyConstraint('port_id', 'ts', name=op.f('pk_port_congestion_metric'))
    )
    op.create_index('ix_port_congestion_metric_port_id_ts', 'port_congestion_metric', ['port_id', 'ts'], unique=False)
    op.create_table('port_tide_observation',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tide_height_m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_port_tide_observation_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], name=op.f('fk_port_tide_observation_port_id_port')),
    sa.PrimaryKeyConstraint('port_id', 'ts', name=op.f('pk_port_tide_observation'))
    )
    op.create_index('ix_port_tide_observation_port_id_ts', 'port_tide_observation', ['port_id', 'ts'], unique=False)
    op.create_table('port_weather_observation',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wind_speed_ms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wave_height_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('visibility_m', sa.Integer(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_port_weather_observation_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], name=op.f('fk_port_weather_observation_port_id_port')),
    sa.PrimaryKeyConstraint('port_id', 'ts', name=op.f('pk_port_weather_observation'))
    )
    op.create_index('ix_port_weather_observation_port_id_ts', 'port_weather_observation', ['port_id', 'ts'], unique=False)
    op.create_table('route_freight_rate',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('vessel_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_basis', sa.Enum('VOYAGE_USD_PER_TONNE', 'TIME_CHARTER_USD_PER_DAY', name='rate_basis'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_route_freight_rate_ingestion_run_id_ingestion_run')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_route_freight_rate_route_id_route')),
    sa.ForeignKeyConstraint(['vessel_type_id'], ['vessel_type.id'], name=op.f('fk_route_freight_rate_vessel_type_id_vessel_type')),
    sa.PrimaryKeyConstraint('route_id', 'vessel_type_id', 'rate_basis', 'ts', name=op.f('pk_route_freight_rate'))
    )
    op.create_index('ix_route_freight_rate_route_id_vessel_type_id_ts', 'route_freight_rate', ['route_id', 'vessel_type_id', 'ts'], unique=False)
    op.create_table('vessel_position',
    sa.Column('imo', sa.String(length=7), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('sog_kn', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cog_deg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nav_status', sa.String(length=32), nullable=True),
    sa.Column('destination_unlocode', sa.String(length=5), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imo'], ['vessel.imo'], name=op.f('fk_vessel_position_imo_vessel')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.id'], name=op.f('fk_vessel_position_ingestion_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('imo', 'ts', name=op.f('pk_vessel_position'))
    )
    op.create_index('ix_vessel_position_imo_ts', 'vessel_position', ['imo', 'ts'], unique=False)
    op.create_table('forecast_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charter_enquiry_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('vessel_type_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='run_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['charter_enquiry_id'], ['charter_enquiry.id'], name=op.f('fk_forecast_run_charter_enquiry_id_charter_enquiry')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_forecast_run_route_id_route')),
    sa.ForeignKeyConstraint(['vessel_type_id'], ['vessel_type.id'], name=op.f('fk_forecast_run_vessel_type_id_vessel_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_run'))
    )
    op.create_index('ix_forecast_run_route_id_vessel_type_id_requested_at', 'forecast_run', ['route_id', 'vessel_type_id', 'requested_at'], unique=False)
    op.create_table('forecast_point',
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('target_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('p10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('p50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('p90', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_run.id'], name=op.f('fk_forecast_point_forecast_run_id_forecast_run')),
    sa.PrimaryKeyConstraint('forecast_run_id', 'target_ts', name=op.f('pk_forecast_point'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_point')
    op.drop_index('ix_forecast_run_route_id_vessel_type_id_requested_at', table_name='forecast_run')
    op.drop_table('forecast_run')
    op.drop_index('ix_vessel_position_imo_ts', table_name='vessel_position')
    op.drop_table('vessel_position')
    op.drop_index('ix_route_freight_rate_route_id_vessel_type_id_ts', table_name='route_freight_rate')
    op.drop_table('route_freight_rate')
    op.drop_index('ix_port_weather_observation_port_id_ts', table_name='port_weather_observation')
    op.drop_table('port_weather_observation')
    op.drop_index('ix_port_tide_observation_port_id_ts', table_name='port_tide_observation')
    op.drop_table('port_tide_observation')
    op.drop_index('ix_port_congestion_metric_port_id_ts', table_name='port_congestion_metric')
    op.drop_table('port_congestion_metric')
    op.drop_index('ix_port_call_port_id_arrival_at', table_name='port_call')
    op.drop_table('port_call')
    op.drop_index(op.f('ix_charter_enquiry_route_id'), table_name='charter_enquiry')
    op.drop_table('charter_enquiry')
    op.drop_index('ix_bunker_price_port_id_fuel_grade_ts', table_name='bunker_price')
    op.drop_table('bunker_price')
    op.drop_index('ix_baltic_index_value_index_code_ts', table_name='baltic_index_value')
    op.drop_table('baltic_index_value')
    op.drop_table('vessel')
    op.drop_index(op.f('ix_route_origin_port_id'), table_name='route')
    op.drop_index(op.f('ix_route_destination_port_id'), table_name='route')
    op.drop_table('route')
    op.drop_index('ix_ingestion_run_data_source_id_started_at', table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_table('vessel_type')
    op.drop_table('port')
    op.drop_table('data_source')
    op.drop_table('cargo_type')
    # ### end Alembic commands ###
